---
title: "Regressione Misurazione vs Simulazione"
author: "Matteo Lonardi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales) # Per gestire meglio le scale dei grafici
library(plotly)
library(tidyverse)
library(modelr)
library(minpack.lm)
```

```{r}
dfm = read.table("sipm_alpha_bias_32V_2.csv", header = T, sep = ",")%>% mutate(TIME_us = TIME * 1e6, t_rel = TIME_us-0.568)
dfs = read.table("voltagemode_update_current_SiPM.txt", header = T) %>% 
  mutate(TIME_us = time * 1e6, t_rel = TIME_us-1.784) %>% 
  rename(CH1 = V.vout.) %>% 
  select(!time) 
```

```{r}
# Creazione del grafico nativo con sovrapposizione corretta
p_plotly <- plot_ly() %>%
  
  # Traccia 1
  add_lines(data = dfm, 
            x = ~TIME_us, 
            y = ~CH1, 
            name = 'SiPM con partielle alpha', 
            line = list(color = "black", width = 1.5)) %>%
  
  # Traccia 2
  add_lines(data = dfs, 
            x = ~TIME_us, 
            y = ~CH1, 
            name = 'Simulazione', 
            line = list(color = 'red', width = 1.5)) %>%
  
  # Layout e titoli 
  layout(
    title = list(
      text = paste0("<b>Confronto Impulsi simulazione vs misurazione</b><br>")
    ),
    xaxis = list(title = "Tempo [\u03bc s]", gridcolor = "#f0f0f0"),
    yaxis = list(title = "Ampiezza [V]", gridcolor = "#f0f0f0"),
    legend = list(
      orientation = 'h', 
      x = 0.5, 
      xanchor = 'center', 
      y = -0.35            
    ),
    margin = list(t = 80, b = 120), 
    plot_bgcolor = "white" 
  )

# Visualizza il grafico
p_plotly
```

```{r}
dfm = read.table("sipm_alpha_bias_32V_2.csv", header = T, sep = ",")%>% mutate(TIME_us = TIME * 1e6, t_rel = TIME_us-0.568)
dfs = read.table("voltagemode_update_current_SiPM.txt", header = T) %>% 
  mutate(TIME_us = time * 1e6, t_rel = TIME_us-1.784) %>% 
  rename(CH1 = V.vout.) %>% 
  select(!time) 
```

```{r}
# Creazione del grafico nativo con sovrapposizione corretta
p_plotly <- plot_ly() %>%
  
  # Traccia 1
  add_lines(data = dfm, 
            x = ~t_rel, 
            y = ~CH1, 
            name = 'SiPM con partielle alpha', 
            line = list(color = "black", width = 1.5)) %>%
  
  # Traccia 2
  add_lines(data = dfs, 
            x = ~t_rel, 
            y = ~CH1, 
            name = 'Simulazione', 
            line = list(color = 'red', width = 1.5)) %>%
  
  # Layout e titoli 
  layout(
    title = list(
      text = paste0("<b>Confronto Impulsi simulazione vs misurazione</b><br>")
    ),
    xaxis = list(title = "Tempo [\u03bc s]", gridcolor = "#f0f0f0"),
    yaxis = list(title = "Ampiezza [V]", gridcolor = "#f0f0f0"),
    legend = list(
      orientation = 'h', 
      x = 0.5, 
      xanchor = 'center', 
      y = -0.35            
    ),
    margin = list(t = 80, b = 120), 
    plot_bgcolor = "white" 
  )

# Visualizza il grafico
p_plotly
```

```{r}
dfs <- dfs %>% filter(t_rel > 0)
dfm <- dfm %>% filter(t_rel > 0)
```

```{r}
# Creazione del grafico nativo con sovrapposizione corretta
p_plotly <- plot_ly() %>%
  
  # Traccia 1
  add_lines(data = dfm, 
            x = ~t_rel, 
            y = ~CH1, 
            name = 'SiPM con partielle alpha', 
            line = list(color = "black", width = 1.5)) %>%
  
  # Traccia 2
  add_lines(data = dfs, 
            x = ~t_rel, 
            y = ~CH1, 
            name = 'Simulazione', 
            line = list(color = 'red', width = 1.5)) %>%
  
  # Layout e titoli 
  layout(
    title = list(
      text = paste0("<b>Confronto Impulsi simulazione vs misurazione</b><br>")
    ),
    xaxis = list(title = "Tempo [\u03bc s]", gridcolor = "#f0f0f0"),
    yaxis = list(title = "Ampiezza [V]", gridcolor = "#f0f0f0"),
    legend = list(
      orientation = 'h', 
      x = 0.5, 
      xanchor = 'center', 
      y = -0.35            
    ),
    margin = list(t = 80, b = 120), 
    plot_bgcolor = "white" 
  )

# Visualizza il grafico
p_plotly
```

```{r}
fits <- nlsLM(CH1 ~ A * exp(-t_rel / tau) + Offset, 
               data = dfs, 
               start = list(A = 1.2, tau = 5,Offset = 0.01),
               control = nls.control(maxiter = 1000))

fitm <- nlsLM(CH1 ~ A * exp(-t_rel / tau) + Offset, 
               data = dfm, 
               start = list(A = 1.2, tau = 5,Offset = 0.01),
               control = nls.control(maxiter = 1000))
fits #Regressione espoenziale simulazione
```
```{r}
fitm #Regressione esponenziale misurazione
```
```{r}
# Calcolo differenza percentuale tra le due regressioni
taus = as.numeric(coef(fits)["tau"])
taum = as.numeric(coef(fitm)["tau"])

dif = (abs(taus-taum)/taum)*100
dif
```



