This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./Prova.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Prova.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (348 comparisons).
Generating output file Prova.acr....done (48 lines written, 0 warnings).
Output written in Prova.acr.
Transcript written in Prova.alg.
